language: android
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
before_install:
  - chmod +x gradlew
script: ./gradlew build -x test
